name: Keep Render Alive
on:
  schedule:
    - cron: '*/10 * * * *' # Каждые 10 минут
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping the server
      run: curl -I https://friendship-check.onrender.com